In [39]:
import numpy as np
import pandas as pd

In [40]:
application_data=pd.read_csv("../data/raw/application_train.csv")

In [41]:
application_data.shape

(307511, 122)

In [42]:
application_data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [43]:
bureau_data=pd.read_csv("../data/raw/bureau.csv")

In [44]:
bureau_data.shape

(1716428, 17)

In [45]:
bureau_data.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [46]:
application_data['TARGET'].value_counts(normalize=True)

TARGET
0    0.919271
1    0.080729
Name: proportion, dtype: float64

In [47]:
application_data.isnull().sum().sort_values(ascending=False).head(20)

COMMONAREA_AVG              214865
COMMONAREA_MODE             214865
COMMONAREA_MEDI             214865
NONLIVINGAPARTMENTS_MEDI    213514
NONLIVINGAPARTMENTS_MODE    213514
NONLIVINGAPARTMENTS_AVG     213514
FONDKAPREMONT_MODE          210295
LIVINGAPARTMENTS_AVG        210199
LIVINGAPARTMENTS_MEDI       210199
LIVINGAPARTMENTS_MODE       210199
FLOORSMIN_MODE              208642
FLOORSMIN_AVG               208642
FLOORSMIN_MEDI              208642
YEARS_BUILD_AVG             204488
YEARS_BUILD_MODE            204488
YEARS_BUILD_MEDI            204488
OWN_CAR_AGE                 202929
LANDAREA_MEDI               182590
LANDAREA_AVG                182590
LANDAREA_MODE               182590
dtype: int64

In [48]:
bureau_data.groupby('SK_ID_CURR').size().describe()

count    305811.000000
mean          5.612709
std           4.430354
min           1.000000
25%           2.000000
50%           4.000000
75%           8.000000
max         116.000000
dtype: float64

In [49]:
bureau_data.isnull().sum().sort_values(ascending=False).head(10)

AMT_ANNUITY               1226791
AMT_CREDIT_MAX_OVERDUE    1124488
DAYS_ENDDATE_FACT          633653
AMT_CREDIT_SUM_LIMIT       591780
AMT_CREDIT_SUM_DEBT        257669
DAYS_CREDIT_ENDDATE        105553
AMT_CREDIT_SUM                 13
SK_ID_CURR                      0
SK_ID_BUREAU                    0
CREDIT_DAY_OVERDUE              0
dtype: int64

In [50]:
print(bureau_data.dtypes)

SK_ID_CURR                  int64
SK_ID_BUREAU                int64
CREDIT_ACTIVE              object
CREDIT_CURRENCY            object
DAYS_CREDIT                 int64
CREDIT_DAY_OVERDUE          int64
DAYS_CREDIT_ENDDATE       float64
DAYS_ENDDATE_FACT         float64
AMT_CREDIT_MAX_OVERDUE    float64
CNT_CREDIT_PROLONG          int64
AMT_CREDIT_SUM            float64
AMT_CREDIT_SUM_DEBT       float64
AMT_CREDIT_SUM_LIMIT      float64
AMT_CREDIT_SUM_OVERDUE    float64
CREDIT_TYPE                object
DAYS_CREDIT_UPDATE          int64
AMT_ANNUITY               float64
dtype: object

In [51]:
bureau_agg = bureau_data.groupby('SK_ID_CURR').agg(
    BUREAU_LOAN_COUNT=('SK_ID_BUREAU', 'count'),
    BUREAU_AMT_CREDIT_SUM=('AMT_CREDIT_SUM', 'sum'),
    BUREAU_AMT_OVERDUE_SUM=('AMT_CREDIT_SUM_OVERDUE', 'sum'),
    BUREAU_AMT_OVERDUE_MAX=('AMT_CREDIT_SUM_OVERDUE', 'max'),
    BUREAU_DAYS_OVERDUE_MAX=('CREDIT_DAY_OVERDUE', 'max'),
    BUREAU_DELINQUENT_COUNT=('CREDIT_DAY_OVERDUE', lambda x: (x > 0).sum())
).reset_index()

In [52]:
bureau_agg.head()

,SK_ID_CURR,BUREAU_LOAN_COUNT,BUREAU_AMT_CREDIT_SUM,BUREAU_AMT_OVERDUE_SUM,BUREAU_AMT_OVERDUE_MAX,BUREAU_DAYS_OVERDUE_MAX,BUREAU_DELINQUENT_COUNT
0,100001,7,1453365.000,0.0,0.0,0,0
1,100002,8,865055.565,0.0,0.0,0,0
2,100003,4,1017400.500,0.0,0.0,0,0
3,100004,2,189037.800,0.0,0.0,0,0
4,100005,3,657126.000,0.0,0.0,0,0

In [53]:
print(bureau_data['CREDIT_DAY_OVERDUE'].value_counts().head(10))

CREDIT_DAY_OVERDUE
0     1712211
30        311
60        126
13        103
8         103
9          93
7          92
14         91
17         77
11         75
Name: count, dtype: int64

In [54]:
print(bureau_data['AMT_CREDIT_SUM_OVERDUE'].describe())

count    1.716428e+06
mean     3.791276e+01
std      5.937650e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.756681e+06
Name: AMT_CREDIT_SUM_OVERDUE, dtype: float64

In [55]:
df = application_data.merge(bureau_agg, on='SK_ID_CURR', how='left')
print(df.shape)
print(df[['BUREAU_LOAN_COUNT','BUREAU_AMT_OVERDUE_SUM']].isnull().sum())

(307511, 128)
BUREAU_LOAN_COUNT         44020
BUREAU_AMT_OVERDUE_SUM    44020
dtype: int64

In [56]:
df['BUREAU_NO_HISTORY'] = df['BUREAU_LOAN_COUNT'].isnull().astype(int)

In [57]:
bureau_cols = ['BUREAU_LOAN_COUNT', 'BUREAU_AMT_CREDIT_SUM', 
               'BUREAU_AMT_OVERDUE_SUM', 'BUREAU_AMT_OVERDUE_MAX',
               'BUREAU_DAYS_OVERDUE_MAX', 'BUREAU_DELINQUENT_COUNT']

df[bureau_cols] = df[bureau_cols].fillna(0)

In [58]:
print(df.isnull().sum()[df.isnull().sum() > 0].shape)
print(df['BUREAU_NO_HISTORY'].value_counts())

(67,)
BUREAU_NO_HISTORY
0    263491
1     44020
Name: count, dtype: int64

In [ ]:
split_threshold = df['DAYS_ID_PUBLISH'].quantile(0.80)

train = df[df['DAYS_ID_PUBLISH'] <= split_threshold].copy()
test = df[df['DAYS_ID_PUBLISH'] > split_threshold].copy()

print(train.shape, test.shape)
print(train['TARGET'].mean(), test['TARGET'].mean())

(246010, 129) (61501, 129)
0.07592780781269054 0.09993333441732655

In [60]:
df['DAYS_EMPLOYED'].describe()

count    307511.000000
mean      63815.045904
std      141275.766519
min      -17912.000000
25%       -2760.000000
50%       -1213.000000
75%        -289.000000
max      365243.000000
Name: DAYS_EMPLOYED, dtype: float64

In [ ]:
df['DAYS_EMPLOYED_ANOMALY'] = df['DAYS_EMPLOYED'].apply(lambda x: 1 if x == 365243 else 0)
df['DAYS_EMPLOYED'] = df['DAYS_EMPLOYED'].replace(365243, np.nan)

C:\Users\Aryan\AppData\Local\Temp\ipykernel_10560\642231561.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DAYS_EMPLOYED'].replace(365243, np.nan, inplace=True)

In [62]:
df[df['DAYS_EMPLOYED'].isnull()].shape[0] / df.shape[0] * 100

18.00716071945394

In [63]:
cols = ['DAYS_BIRTH', 'DAYS_EMPLOYED', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']
train[cols].isnull().sum() / len(train) * 100

DAYS_BIRTH        0.000000
DAYS_EMPLOYED     0.000000
EXT_SOURCE_1     57.353766
EXT_SOURCE_2      0.210967
EXT_SOURCE_3     18.469981
dtype: float64

In [64]:
train['EXT_SOURCE_1_MISSING'] = train['EXT_SOURCE_1'].isnull().astype(int)
train.groupby('EXT_SOURCE_1_MISSING')['TARGET'].mean()

EXT_SOURCE_1_MISSING
0    0.070524
1    0.079946
Name: TARGET, dtype: float64

In [65]:
train.drop('EXT_SOURCE_1_MISSING', axis=1, inplace=True)

In [66]:
from optbinning import OptimalBinning

In [67]:
binning_dict = {}

for feature in cols:
    optb = OptimalBinning(name=feature, dtype="numerical", solver="cp")
    optb.fit(train[feature], train["TARGET"])

    train[feature + "_WoE"] = optb.transform(train[feature], metric="woe")
    test[feature + "_WoE"] = optb.transform(test[feature], metric="woe")

    binning_dict[feature] = optb

In [68]:
woe_cols = [col + '_WoE' for col in cols]
train[woe_cols].head()

,DAYS_BIRTH_WoE,DAYS_EMPLOYED_WoE,EXT_SOURCE_1_WoE,EXT_SOURCE_2_WoE,EXT_SOURCE_3_WoE
0,-0.387803,-0.351609,-0.681536,-0.385678,-1.166429
2,0.172281,-0.344262,0.000000,0.199728,0.855819
3,0.172281,0.103952,0.000000,0.385397,0.000000
4,0.321429,0.103952,0.000000,-0.385678,0.000000
7,0.172281,-0.447395,0.000000,0.814104,0.327345

In [69]:
train[woe_cols].isnull().sum()

DAYS_BIRTH_WoE       0
DAYS_EMPLOYED_WoE    0
EXT_SOURCE_1_WoE     0
EXT_SOURCE_2_WoE     0
EXT_SOURCE_3_WoE     0
dtype: int64

In [70]:
print(binning_dict['EXT_SOURCE_1'].binning_table.build())

                 Bin   Count  Count (%)  Non-event  Event  Event rate  \
0       (-inf, 0.30)   20195   0.082090      17373   2822    0.139738
1       [0.30, 0.40)   15437   0.062749      14090   1347    0.087258
2       [0.40, 0.50)   14518   0.059014      13552    966    0.066538
3       [0.50, 0.60)   16040   0.065201      15186    854    0.053242
4       [0.60, 0.70)   14963   0.060823      14251    712    0.047584
5        [0.70, inf)   23761   0.096586      23063    698    0.029376
6            Special       0   0.000000          0      0    0.000000
7            Missing  141096   0.573538     129816  11280    0.079946
Totals                246010   1.000000     227331  18679    0.075928

             WoE        IV        JS
0      -0.681536  0.050882  0.006240
1      -0.151422  0.001534  0.000192
2       0.142118  0.001122  0.000140
3       0.379191  0.007994  0.000993
4       0.497497  0.012224  0.001512
5       0.998759  0.064003  0.007684
6            0.0  0.000000  0.000000
7       -0.05592  0.001837  0.000230
Totals            0.139596  0.016991

In [72]:
train[train['EXT_SOURCE_1_WoE'] == 0.0]['EXT_SOURCE_1'].isnull().sum()

np.int64(141096)

In [73]:
train[train['EXT_SOURCE_1_WoE'] == 0.0].shape[0]

141096

In [74]:
for feature in cols:
    bt = binning_dict[feature].binning_table.build()
    iv = bt['IV'].iloc[-1]
    print(f"{feature}: IV = {iv:.4f}")

DAYS_BIRTH: IV = 0.0853
DAYS_EMPLOYED: IV = 0.1093
EXT_SOURCE_1: IV = 0.1396
EXT_SOURCE_2: IV = 0.3119
EXT_SOURCE_3: IV = 0.3282

In [76]:
X_train = train[woe_cols]
y_train = train['TARGET']
X_test = test[woe_cols]
y_test = test['TARGET']

In [79]:
from sklearn import linear_model
log_reg = linear_model.LogisticRegression(class_weight='balanced', max_iter=1000)
log_reg.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [83]:
prediction_probabilities = log_reg.predict_proba(X_test)[:, 1]

In [95]:
from sklearn.metrics import roc_auc_score

In [96]:
roc_auc_score = roc_auc_score(y_test, prediction_probabilities)
print(f"ROC AUC Score: {roc_auc_score:.4f}")

ROC AUC Score: 0.7188

In [85]:
gini = 2 * roc_auc_score(y_test, prediction_probabilities) - 1
print(f"Gini Coefficient: {gini:.4f}")

Gini Coefficient: 0.4376

In [86]:
from scipy.stats import ks_2samp

In [87]:
ks_statistic, p_value = ks_2samp(prediction_probabilities[y_test == 0], prediction_probabilities[y_test == 1])

In [88]:
print(f"KS Statistic: {ks_statistic:.4f}, p-value: {p_value:.4f}")

KS Statistic: 0.3292, p-value: 0.0000

Score = Offset + Factor × ln(Odds)

In [97]:
PDO = 20
Factor = PDO / np.log(2)
offset= 600 - Factor * np.log(50)
print(f"Factor: {Factor:.4f}, Offset: {offset:.4f}")

Factor: 28.8539, Offset: 487.1229

In [100]:
test['SCORE'] = offset + Factor * np.log((1 - prediction_probabilities) / prediction_probabilities)
test[['SK_ID_CURR', 'SCORE']].head()

    SK_ID_CURR       SCORE
1       100003  486.225407
5       100008  486.738883
6       100009  529.820137
10      100014  479.881542
15      100019  474.369845

In [101]:
test['SCORE'].describe()

count    61501.000000
mean       488.717464
std         25.872887
min        405.623101
25%        471.207398
50%        489.367465
75%        507.094782
max        567.955165
Name: SCORE, dtype: float64

In [102]:
test[['SK_ID_CURR', 'SCORE']].head(10)

    SK_ID_CURR       SCORE
1       100003  486.225407
5       100008  486.738883
6       100009  529.820137
10      100014  479.881542
15      100019  474.369845
18      100022  525.980122
36      100043  536.277398
40      100047  465.348919
41      100048  448.986445
45      100052  479.751090